name: Deploy to GitHub Pages

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    container:
      image: node:16.16.0
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/install
      - name: 'Download @siemens/ix-brand-theme'
        run: |
          ROOT=$(pwd)
          cd ./packages/html-test-app/public/additional-theme
          echo "@siemens:registry=https://code.siemens.com/api/v4/projects/249177/packages/npm/" >> .npmrc
          echo "//code.siemens.com/api/v4/projects/249177/packages/npm/:_authToken=${{ secrets.READ_CSC_TOKEN }}" >> .npmrc
          npm install @siemens/ix-brand-theme --no-save
          sed -i -e '/\"publishConfig\"/,/}/ d; /^$/d' node_modules/@siemens/ix-brand-theme/package.json
          mv node_modules/@siemens ./
          cd ROOT
      - uses: ./.github/workflows/actions/build
      - name: 'Build documentation'
        run: |
          yarn workspace documentation run build
      - name: 'Copy documentation'
        run: |
          cp -R ./packages/documentation/build/. ./public
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: ix.siemens.io
