name: Deploy to PROD GitHub Pages

on:
  workflow_dispatch:
    inputs:
      confirm_deployment:
        description: 'Please confirm PROD deployment'
        required: true
        type: boolean

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    container:
      image: node:16.16.0
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/install
      - uses: ./.github/workflows/actions/build
      - name: 'Download @siemens/ix-brand-theme'
        run: |
          ROOT=$(pwd)
          cd ./packages/html-test-app/src/public/additional-theme
          echo "@siemens:registry=https://code.siemens.com/api/v4/projects/249177/packages/npm/" >> .npmrc
          echo "//code.siemens.com/api/v4/projects/249177/packages/npm/:_authToken=${{ secrets.READ_CSC_TOKEN }}" >> .npmrc
          curl --header "PRIVATE-TOKEN: ${{ secrets.READ_CSC_TOKEN }}" $(yarn info @siemens/ix-brand-theme dist.tarball | sed -n 2p) -o ix-brand-theme.tgz
          tar zxvf ix-brand-theme.tgz
          mv package ix-brand-theme
          rm ix-brand-theme.tgz
          sed -i -e '/\"publishConfig\"/,/}/ d; /^$/d' ix-brand-theme/package.json
          rm ix-brand-theme/package.json-e
          cp -R ./ix-brand-theme $ROOT/node_modules/@siemens

      - name: 'Build documentation for PROD instance'
        run: |
          yarn workspace documentation run build

      - name: 'Copy PROD documentation'
        run: |
          cp -R ./packages/documentation/build/. ./public

      - name: Deploy documentation to PROD instance
        if: ${{ github.input.confirm_deployment == true }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: ix.siemens.io
