name: Publish Beta

on:
  push:
    branches:
      - workflow/publish

concurrency:
  group: prepublish-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build-lib:
    uses: ./.github/workflows/build.yml
  deploy:
    needs: [build-lib]
    runs-on: ubuntu-latest
    container:
      image: node:16.16.0
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v3
      - name: Publish beta version to npmjs.org
        run: ls ./packages/core/dist
